### ISSUE TITLE
argocd support 

### ISSUE THREAD

**Issue by chris93111** [DevOpsHiveHQ/kustomize-plugin-merger#74]
Hi 

This plugin can work with argocd ?

the krm function use docker for build manifests with embedded bin, but can't use docker in argocd

any suggestion ?

Thanks

**Comment by aabouzaid** [comment]
Hi @chris93111 the plugin is also available as an Exec KRM function and can be downloaded from the release page https://github.com/DevOpsHiveHQ/kustomize-plugin-merger/releases

You will find the Exec KRM function section in all examples, but it's commented. E.g.
https://github.com/DevOpsHiveHQ/kustomize-plugin-merger/tree/62e552e/examples/manifest-lists-without-schema#manifest

All that you need to do is download the binary to the ArgoCD system and it will work:

```
apiVersion: generators.kustomize.aabouzaid.com/v1alpha1
kind: Merger
metadata:
  name: merge
  annotations:
    # Exec KRM functions.
    config.kubernetes.io/function: |
      exec:
        path: kustomize-plugin-merger
spec:
[...]
```

And the rest under `spec` is the same.

**Comment by aabouzaid** [comment]
Hi @chris93111 the plugin is also available as an Exec KRM function and can be downloaded from the release page https://github.com/DevOpsHiveHQ/kustomize-plugin-merger/releases

You will find the Exec KRM function section in all examples, but it's commented. E.g.
https://github.com/DevOpsHiveHQ/kustomize-plugin-merger/tree/d61661b/examples/manifest-lists-without-schema#manifest

All that you need to do is download the binary to the ArgoCD system and it will work:

```
apiVersion: generators.kustomize.devopshive.net/v1alpha1
kind: Merger
metadata:
  name: merge
  annotations:
    # Exec KRM functions.
    config.kubernetes.io/function: |
      exec:
        path: kustomize-plugin-merger
spec:
[...]
```

And the rest under `spec` is the same.
